### ISSUE TITLE
Statistics for e2e app

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#2174] opened 2021-08-03 06:12 UTC
We have no statistics how many test coverage we have for our e2e test app.
-> show statistics for e2e test coverage

Ideal we also can combine statistics of unit and e2e test coverage.
-> investigate if the combination of both is possible.

**Comment by rafalgamon** [comment] 2021-09-14 07:20
All the logic that generates the report is ready.
The problem is that the stats are only generated for the e2e folder and not for the core. From what I was able to find on the internet, this solution can be in the files that are includes and excludes in the `nyc` configuration. But I try it and still I don't have any working solution.

**Comment by hardl** [comment] 2022-09-13 12:26
de-prioritized, maybe can be revisited later, closing for now

**Closed by hardl** 2022-09-13 12:26 UTC
Labels: WIP, internal, don't talk about it 🤫
