### ISSUE TITLE
iframeCreationInterceptor callback not called when navigating with the browser back/forward buttons

### ISSUE THREAD

**Issue by eucaos** [SAP/luigi#1998] opened 2021-04-27 06:57 UTC
**Description**

We are using the **iframeCreationInterceptor** callBack to pass all Luigi Search query parameters to the micro-application iframe. <br/>
This works fine for the happy flow, but when navigating with the browser Back/Forward buttons the **iframeCreationInterceptor** callBack is not called anymore. <br/>

For the Luigi configuration we’re using virtualTree: true and pathSegment viewGroup navigationContext with the same value<br/>

Tested on: 
Google Chrome Version 90.0.4430.85 (Official Build) (arm64) 
Safari Version 14.0.2 (16610.3.7.1.9) 
Microsoft Edge Version 90.0.818.42 (Official build) (64-bit) 

OS : MacOS Big Sur 11.1 

**Expected result**

When navigating with the browser Back/Forward buttons between a micro-application urls, the **iframeCreationInterceptor** callBack is called.

**Actual result**

When navigating with the browser Back/Forward buttons between a micro-application urls, the **iframeCreationInterceptor** callBack is not called anymore.

**Steps to reproduce**

We have a micro-application that is loaded into a Luigi Iframe.

1. Go to a LUIGI url like http://localhost:3000/items 
2. Search for an item, LUIGI url becomes  like http://localhost:3000/items?name=search_text
  (at this step iframeCreationInterceptor callback is called and we can add all the LUIGI search query parameters to the iframe url)
3. Go back using browser back buttons 
4. Go forward using browser forward button 
   (at this step iframeCreationInterceptor callback is not called anymore and we can't provide  the LUIGI search query parameters to the iframe) 
 
**Troubleshooting**

Tried to alter the iframe src after being aded tot the DOM, but this alters the Browser navigation history natural order. <br/>
There is a recommended way to pass parameters down but is not generic and it involves defining Luigi static nodes with the params manually specified. 
We can't afford to manually do this for every route in the micro-application. <br/>

iframeCreationInterceptor hack was suggested here https://luigi-project.slack.com/archives/CMV4EME3G/p1606990004196900 <br/>
the queryparameters passing down to the iframe when using virtualTree:true was mentioned here as well https://luigi-project.slack.com/archives/CMV4EME3G/p1594815960141400

**Comment by eucaos** [comment] 2021-05-17 07:01
I see you took this bug into the sprint for sometime but nobody dares to tackle it :D

**Comment by JohannesDoberer** [comment] 2021-05-18 19:39
Hello,
yes, it looks like :).

I can reproduce your issue partially.

The behaviour comes with the viewgroup.
If you have nodes with the same viewgroup and you navigate between them there won't be a new iframe created, means no iframeCreationInterceptor. Neither if you do the happy flow, which I guess happens via click, nor by using back/forward button.
The opposite in both cases if I don't use viewgroups.
This behaviour is build by design (and not a bug).
In my configuration it doesn't matter if you have a virtual tree or not.
Maybe you can share a sample config if you get a different behaviour.

Do you know the property [isolateView](https://docs.luigi-project.io/docs/navigation-advanced/?section=defaultsisolateview)? Does it help you?
Of course to not use viewgroups in your specific case would help, but I guess it is not an option for you?

Best Regards

**Comment by JohannesDoberer** [comment] 2021-05-27 07:59
Hello,

does this suggestions help you?
Did you find a solution?

Best regards

**Comment by JohannesDoberer** [comment] 2021-05-28 06:43
I will close this issue.
If there are any questions feel free to reopen it.

**Closed by JohannesDoberer** 2021-05-28 06:43 UTC
Labels: bug
