### ISSUE TITLE
The 'popstate' event is emitted twice into the iframe

### ISSUE THREAD

**Issue by parostatkiem** [SAP/luigi#1978] opened 2021-04-13 10:00 UTC
**Description**
Whenever a navigation link from the nav (top or left) is clicked or the `LuigiClient.linkManager().navigate()` action is executed from within the iframe, the `popstate` event is fired several times inside the client app (iframe). It’s sent just once in the native context (outside the iframe) which is correct. 

LuigiClient version: 1.12.1
LuigiCore version: 1.12.1
Browser: any (probably)
Microfrontend framework: Tested on React.js; should be reproducible on any, including the bare Javascript

**Expected result**
The `popstate` event is emitted to the microfrontend once.

**Actual result**
The `popstate` event is emitted to the microfrontend twice.

**Steps to reproduce**

1. Using the browser dev console, add the `popstate` event listener to the main window
  ```javascript
  window.addEventListener('popstate', arg => {
    console.log('Browser popstate happened', arg);
  });
  ```

2. Add `popstate` event listener to the microfrontend code with an additional `console.log()` to make sure the listener is added only once
  
 ```javascript
console.log('ADDING IFRAME EVENT LISTENER');
window.addEventListener('popstate', e => {
  console.log('iframe popstate event came', e.target.location);
});
  ```

Then click some links from the Luigi navigation or navigate from within the iframe using `LuigiClient.linkManager().navigate()`. You'll see the _iframe popstate event came_ message appearing twice every time you clicked, with exactly the same `location` data.
![image](https://user-images.githubusercontent.com/22825433/114534910-c8ca9080-9c4f-11eb-9b77-817e0701a80e.png)

**Troubleshooting**

**Comment by stanleychh** [comment] 2021-05-20 14:31
Hi parostatkiem, I close this ticket because it seems not a bug from Luigi side after investigation. Not able to reproduce this issue with the basic(simplest) setup. Please double-check your micro-frontend applications.

Please feel free to drop a comment or contact me directly if this is still a case to you. Thanks.

**Closed by stanleychh** 2021-05-20 14:31 UTC
Labels: bug
