### ISSUE TITLE
Pressing ESC with two overlaying modals leads to error 

### ISSUE THREAD

**Issue by MichaelBaySAP** [SAP/luigi#3536] opened 2023-11-20 15:24 UTC
This issue only occurs in our application. We have tested that it does not always occur. In our app, I open a modal A on top of another modal B. Pressing ESC closes modal A. Reopen the closed modal A. When reopening the modal A, it appears without content.

**Expected result**

The reopened modal should have content inside.

**Actual result**

The reopened modal does not have content.

I aligned about this issue with Johannes Doberer.

**Comment by MichaelBaySAP** [comment] 2023-11-20 17:11
issue on our side

**Comment by MichaelBaySAP** [comment] 2023-11-22 11:40
After aligning with Johannes Doberer, the issue is indeed on Luigi side

**Comment by littleamigo** [comment] 2023-11-22 11:52
@MichaelBaySAP Why does the problem only occur in our case, unlike the other similar scenario (extension installation) where luigi modals are also stacked in the same way AFAIK?

**Comment by MichaelBaySAP** [comment] 2023-11-22 12:41
@littleamigo Johannes Doberer will firstly fix the issue and then look into why it is not occuring in the other scenario.

**Comment by littleamigo** [comment] 2023-11-22 13:13
> @littleamigo Johannes Doberer will firstly fix the issue and then look into why it is not occuring in the other scenario.

@MichaelBaySAP Well, okay. It does not answer my question though. I would appreciate it if my question was answered.

**Comment by JohannesDoberer** [comment] 2023-11-22 15:39
@littleamigo I can't say, why the content is not shown when you open the 2nd modal again.

I fixed the console error which happens, when you close the 2nd modal by pressing 'esc'.
The root cause is that the wrong modal data will be deleted when you press 'esc', which means in your case, the data from the full screen modal will be deleted.

From Luigi perspective extension installation has the same error. Why it is working on their side idk.

**Maybe** in your case the fullscreen modal has data which are relevant to open the 2nd modal and if these data are deleted it's not possible to open the 2nd modal again. (Only a suggestion)

Should be fixed with the next luigi release.

**Comment by littleamigo** [comment] 2023-11-22 18:54
@JohannesDoberer Apparently, you nailed it because we open the modal with params.

**Closed** 2023-11-30 15:44 UTC
Labels: dxp

**Comment by littleamigo** [comment] 2023-12-01 22:17
Johannes just informed me that this fix will only take effect if @luigi-project/core is also updated to v2.7.3, not just the clients 👍

**Comment by littleamigo** [comment] 2023-12-04 17:52
@JohannesDoberer With 2.7.4 it works now - thanks for the update! (Note: With 2.7.3 we had other issues when loading webcomponents)
